version: '3.8'

services:

  mariadb:
    container_name: development_mariadb
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    networks:
      - network
    volumes:
      - db-config:/etc/mariadb/development
      - db-data:/var/lib/mariadb/development

  nginx:
    container_name: development_nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    networks:
      - network
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    links:
      - php7

  php7:
    container_name: development_php7
    image: php:7-fpm
    restart: always
    networks:
      - network
    volumes:
      - ./nginx/html:/usr/share/nginx/html

networks:
  network:
    driver: bridge

volumes:
  db-config:
  db-data:
